#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=z3Z&u!:lD`e/Xd
#spring.datasource.url=jdbc:mysql://localhost:3306/mdd

server:
  port: 3001

spring:
  application:
    name: mdd
  mvc:
    servlet:
      path: /api
  docker:
    compose:
      enabled: "true"
      file: docker-compose.yml
#  datasource:
#    url:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username:
#    password:

# Enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"