server:
  port: 3001

spring:
  application:
    name: mdd
  mvc:
    servlet:
      path: /api
  docker:
    compose:
      enabled: 'true'
      file: docker-compose.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mdd
    username: myuser
    password: mypassword
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: 'none'
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'

# Enable actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"