services:
  db:
    image: mysql:9.2.0
    container_name: mysql-db
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3307:3306'
#    volumes:
#      - db:/data/db
#
#volumes:
#  db:
#    driver:
#      local